import { Query } from "../src/query";

const testCases: Record<keyof ReturnType<ReturnType<typeof Query>>, Array<() => void>> = {
    add: [],
    addBack: [],
    addClass: [],
    after: [],
    append: [],
    appendTo: [],
    attr: [],
    before: [],
    blur: [],
    change: [],
    children: [],
    clone: [],
    closest: [],
    contextmenu: [],
    css: [],
    data: [],
    dblclick: [],
    each: [],
    empty: [],
    end: [],
    eq: [],
    even: [],
    filter: [],
    find: [],
    first: [],
    focus: [],
    focusin: [],
    focusout: [],
    get: [],
    has: [],
    hasClass: [],
    height: [],
    hide: [],
    hover: [],
    html: [],
    index: [],
    insertAfter: [],
    insertBefore: [],
    is: [],
    keydown: [],
    keypress: [],
    keyup: [],
    last: [],
    length: [],
    map: [],
    mousedown: [],
    mouseenter: [],
    mouseleave: [],
    mousemove: [],
    mouseout: [],
    mouseover: [],
    mouseup: [],
    next: [],
    nextAll: [],
    nextUntil: [],
    not: [],
    odd: [],
    off: [],
    on: [],
    once: [],
    parent: [],
    parents: [],
    parentsUntil: [],
    prepend: [],
    prependTo: [],
    prev: [],
    prevAll: [],
    prevUntil: [],
    pushStack: [],
    ready: [],
    reduce: [],
    remove: [],
    removeAttr: [],
    removeClass: [],
    removeData: [],
    replaceAll: [],
    replaceWith: [],
    select: [],
    siblings: [],
    slice: [],
    submit: [],
    tagName: [],
    text: [],
    toggle: [],
    toggleClass: [],
    uniqueSort: [],
    unload: [],
    unwrap: [],
    val: [],
    wrap: [],
    wrapAll: [],
    wrapInner: [],
    [Symbol.iterator]: []
};

describe("Methods of Query work as expected", () => {
    Object.entries(testCases).forEach(([method, tests]) => {
        tests.forEach((test, index) => {
            it(`Method ${method}, test n.${index} working as expected`, test);
        })
    });
});